---
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.proxmox
    version: ">=1.4.0"
    source: https://galaxy.ansible.com

roles:
  - name: bpbradley.komodo
  - name: geerlingguy.docker
